### ISSUE TITLE
Perform integration tests on the components in the Storybook

### ISSUE THREAD

**Issue by dbpiper** [dbpiper/Euclid#51]
# User Story

As a developer I would like to have fast, yet thorough integration tests on the React components so that we have regression tests in case something breaks and to confirm that features are implemented.

This blocks #50 since it will be using the Cypress storybook integration testing methodology established in this issue as part of its implementation.

**Comment by dbpiper** [comment]
This is related to #45 and should make fixing it much easier, and may even be handled as part of this issue.

**Comment by dbpiper** [comment]
This need to be moved to Sprint 8, I am having an issue with accessing iframes from Cypress this is a well-known problem with Cypress and is discussed in [this GitHub issue](https://github.com/cypress-io/cypress/issues/136). I am trying the workarounds described there, with little success so far.

Specifically, when I try to access the iframe's content it appears to be completely empty to Cypress.

This iframe issue is a big problem because Storybook runs the stories in an iframe which means that a workaround for this **must** be found in order to finish this issue.

**Comment by dbpiper** [comment]
Moving to Sprint 8.

**Comment by dbpiper** [comment]
I found a workaround for the Cypress iframe issue, so I should have no problem implementing this issue in Sprint 8!

**Comment by jmenestr** [comment]
@dbpiper I'm curious as to the workaround you have for the cypress issue?

**Comment by dbpiper** [comment]
Hi, @jmenestr. It is committed in https://github.com/dbpiper/Euclid/tree/GH-51-integration-test-stories. So you may check it out there.

Essentially, it involves finding the iframe src indirectly and then telling Cypress to visit it instead of the main storybook page something like `cy.visit(${storybookUrl}/iframe.html?id=${storybookComponentId})`.
